### ISSUE TITLE
Question on Readme

### ISSUE THREAD

**Issue by basilboli** [Shell-Company/gpt3client#1]
Hello @louisbarrett, thanks for sharing. 

In your readme, you say:

_This is a client for the OpenAI GPT-3 text generation API. The client was generated by GPT-3 itself from a curl statement 🤖._

How did you do this ? 

Did you use any specific OpenAI for this ? 
I have similar use cases for other languages.

Thanks in advance. 

Vasyl

**Comment by basilboli** [comment]
I did tried input like this:

```
Create golang code from below curl snippet: 

curl https://api.openai.com/v1/completions \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer YOUR_API_KEY' \
  -d '{
  "model": "text-davinci-002",
  "prompt": "Say this is a test",
  "max_tokens": 6,
  "temperature": 0
}'

```

but output is far from what you have as a code.
Just interested if you did any fine-tuning, your code looks very well so I am interested to know if it's really generated. 

Thanks.

**Comment by louisbarrett** [comment]
Hi Vasyl, 

In order to get good results, you have to nudge the model in the right direction by adding a little bit of context: 

1. Give the AI a hint what proper code structure looks like, telling it how the file starts is pretty effective for this
2. Tell the AI when and where to start generating the code, adding a 'Code:' heading accomplishes this

Using the tips above I modified your prompt to look like this:
```
Create golang code from below curl snippet the first line of the golang code should be 'package main': 

curl https://api.openai.com/v1/completions \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer YOUR_API_KEY' \
  -d '{
  "model": "text-davinci-002",
  "prompt": "Say this is a test",
  "max_tokens": 6,
  "temperature": 0
}'

Code: 
```

P.S - I'll eventually share a number of techniques to generate code using large language models, but for now you can follow the tips above.

**Comment by basilboli** [comment]
Thank you for your answer.
